//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mongoose {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mongoose.strings", typeof(strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Favorites.
        /// </summary>
        internal static string AddToFavorites {
            get {
                return ResourceManager.GetString("AddToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Information.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library art exhibition information.
        /// </summary>
        internal static string ArtDisplayInformation {
            get {
                return ResourceManager.GetString("ArtDisplayInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Art Display.
        /// </summary>
        internal static string ArtDisplayTitle {
            get {
                return ResourceManager.GetString("ArtDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArtEvent Guide.
        /// </summary>
        internal static string ArtEvent {
            get {
                return ResourceManager.GetString("ArtEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art Info.
        /// </summary>
        internal static string ArtInfoPageTitle {
            get {
                return ResourceManager.GetString("ArtInfoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arts.
        /// </summary>
        internal static string Arts {
            get {
                return ResourceManager.GetString("Arts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  at .
        /// </summary>
        internal static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audience.
        /// </summary>
        internal static string Audience {
            get {
                return ResourceManager.GetString("Audience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Audiences.
        /// </summary>
        internal static string AudienceAll {
            get {
                return ResourceManager.GetString("AudienceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alumni.
        /// </summary>
        internal static string AudienceAlumni {
            get {
                return ResourceManager.GetString("AudienceAlumni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty.
        /// </summary>
        internal static string AudienceFaculty {
            get {
                return ResourceManager.GetString("AudienceFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future Students.
        /// </summary>
        internal static string AudienceFutureStudents {
            get {
                return ResourceManager.GetString("AudienceFutureStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managers.
        /// </summary>
        internal static string AudienceManagers {
            get {
                return ResourceManager.GetString("AudienceManagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parents.
        /// </summary>
        internal static string AudienceParents {
            get {
                return ResourceManager.GetString("AudienceParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string AudienceStaff {
            get {
                return ResourceManager.GetString("AudienceStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        internal static string AudienceStudents {
            get {
                return ResourceManager.GetString("AudienceStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New acquisitions at the Concordia Library.
        /// </summary>
        internal static string BookDisplayInformation {
            get {
                return ResourceManager.GetString("BookDisplayInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Arrivals In The Library.
        /// </summary>
        internal static string BookDisplayTitle {
            get {
                return ResourceManager.GetString("BookDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        internal static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus.
        /// </summary>
        internal static string Campus {
            get {
                return ResourceManager.GetString("Campus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Categories.
        /// </summary>
        internal static string CategoryAll {
            get {
                return ResourceManager.GetString("CategoryAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arts and Culture.
        /// </summary>
        internal static string CategoryArtsAndCulture {
            get {
                return ResourceManager.GetString("CategoryArtsAndCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferences and Lectures.
        /// </summary>
        internal static string CategoryConferencesAndLectures {
            get {
                return ResourceManager.GetString("CategoryConferencesAndLectures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examinations.
        /// </summary>
        internal static string CategoryExaminations {
            get {
                return ResourceManager.GetString("CategoryExaminations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fundraisers.
        /// </summary>
        internal static string CategoryFundraisers {
            get {
                return ResourceManager.GetString("CategoryFundraisers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information And Orientation.
        /// </summary>
        internal static string CategoryInformationOrientation {
            get {
                return ResourceManager.GetString("CategoryInformationOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Events.
        /// </summary>
        internal static string CategoryOtherEvents {
            get {
                return ResourceManager.GetString("CategoryOtherEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religious and Spiritual.
        /// </summary>
        internal static string CategoryReligiousAndSpiritual {
            get {
                return ResourceManager.GetString("CategoryReligiousAndSpiritual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Events.
        /// </summary>
        internal static string CategorySocialEvents {
            get {
                return ResourceManager.GetString("CategorySocialEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports and Wellness.
        /// </summary>
        internal static string CategorySportsAndWellness {
            get {
                return ResourceManager.GetString("CategorySportsAndWellness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshops And Seminars.
        /// </summary>
        internal static string CategoryWorkshopsSeminars {
            get {
                return ResourceManager.GetString("CategoryWorkshopsSeminars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find out what is on reserve for your courses.
        /// </summary>
        internal static string CourseReservesRoomInformation {
            get {
                return ResourceManager.GetString("CourseReservesRoomInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Reserves Room.
        /// </summary>
        internal static string CourseReservesRoomTitle {
            get {
                return ResourceManager.GetString("CourseReservesRoomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently Exploring:.
        /// </summary>
        internal static string CurrentlyExploring {
            get {
                return ResourceManager.GetString("CurrentlyExploring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Beacon.
        /// </summary>
        internal static string DebugBeacon {
            get {
                return ResourceManager.GetString("DebugBeacon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Location.
        /// </summary>
        internal static string DebugLocation {
            get {
                return ResourceManager.GetString("DebugLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        internal static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Info.
        /// </summary>
        internal static string EventInfoPageTitle {
            get {
                return ResourceManager.GetString("EventInfoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        internal static string Explore {
            get {
                return ResourceManager.GetString("Explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string FavoritesClearDay {
            get {
                return ResourceManager.GetString("FavoritesClearDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string FavoritesClearMonth {
            get {
                return ResourceManager.GetString("FavoritesClearMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Weeks.
        /// </summary>
        internal static string FavoritesClearTwoWeeks {
            get {
                return ResourceManager.GetString("FavoritesClearTwoWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string FavoritesClearWeek {
            get {
                return ResourceManager.GetString("FavoritesClearWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically clear my Favorites every.
        /// </summary>
        internal static string FavoritesExpireDate {
            get {
                return ResourceManager.GetString("FavoritesExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to default filters.
        /// </summary>
        internal static string FiltersResetToDefault {
            get {
                return ResourceManager.GetString("FiltersResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset the filters to their default settings?.
        /// </summary>
        internal static string FiltersResetWarning {
            get {
                return ResourceManager.GetString("FiltersResetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me events from these audiences.
        /// </summary>
        internal static string FiltersSettingsAudiencePrompt {
            get {
                return ResourceManager.GetString("FiltersSettingsAudiencePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me events from these categories.
        /// </summary>
        internal static string FiltersSettingsCategoryPrompt {
            get {
                return ResourceManager.GetString("FiltersSettingsCategoryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me events from these units.
        /// </summary>
        internal static string FiltersSettingsUnitPrompt {
            get {
                return ResourceManager.GetString("FiltersSettingsUnitPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some content may not be displayed in your preferred language. Availability depends solely on the event publisher..
        /// </summary>
        internal static string LanguageAvailability {
            get {
                return ResourceManager.GetString("LanguageAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No address.
        /// </summary>
        internal static string NoAddress {
            get {
                return ResourceManager.GetString("NoAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no events for your current building and selected filter(s). Please choose another building or change the filter settings..
        /// </summary>
        internal static string NoEvents {
            get {
                return ResourceManager.GetString("NoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no events in your Favorites list.
        /// </summary>
        internal static string NoFavorites {
            get {
                return ResourceManager.GetString("NoFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current building could not be determined. Please make sure that your GPS is turned on or choose a building manually..
        /// </summary>
        internal static string NoLocationForEventList {
            get {
                return ResourceManager.GetString("NoLocationForEventList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify me when I&apos;m near public arts.
        /// </summary>
        internal static string NotifyArts {
            get {
                return ResourceManager.GetString("NotifyArts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public art notifications use your device&apos;s Bluetooth.
        /// </summary>
        internal static string NotifyArtsDetails {
            get {
                return ResourceManager.GetString("NotifyArtsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify public arts.
        /// </summary>
        internal static string NotifyArtsShort {
            get {
                return ResourceManager.GetString("NotifyArtsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Day.
        /// </summary>
        internal static string NotifyDay {
            get {
                return ResourceManager.GetString("NotifyDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify me with detailed text.
        /// </summary>
        internal static string NotifyDetails {
            get {
                return ResourceManager.GetString("NotifyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn text options off for shorter notifications.
        /// </summary>
        internal static string NotifyDetailsDetails {
            get {
                return ResourceManager.GetString("NotifyDetailsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify with details.
        /// </summary>
        internal static string NotifyDetailsShort {
            get {
                return ResourceManager.GetString("NotifyDetailsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify me of events.
        /// </summary>
        internal static string NotifyEvents {
            get {
                return ResourceManager.GetString("NotifyEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event notifications use your device&apos;s GPS.
        /// </summary>
        internal static string NotifyEventsDetails {
            get {
                return ResourceManager.GetString("NotifyEventsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify events.
        /// </summary>
        internal static string NotifyEventsShort {
            get {
                return ResourceManager.GetString("NotifyEventsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Hour.
        /// </summary>
        internal static string NotifyHour {
            get {
                return ResourceManager.GetString("NotifyHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next 7 Days.
        /// </summary>
        internal static string NotifySevenDays {
            get {
                return ResourceManager.GetString("NotifySevenDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next 6 Hours.
        /// </summary>
        internal static string NotifySixHours {
            get {
                return ResourceManager.GetString("NotifySixHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next 30 Days.
        /// </summary>
        internal static string NotifyThirtyDays {
            get {
                return ResourceManager.GetString("NotifyThirtyDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next 3 Hours.
        /// </summary>
        internal static string NotifyThreeHours {
            get {
                return ResourceManager.GetString("NotifyThreeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONE-TIME.
        /// </summary>
        internal static string Onetime {
            get {
                return ResourceManager.GetString("Onetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONGOING.
        /// </summary>
        internal static string Ongoing {
            get {
                return ResourceManager.GetString("Ongoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        internal static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Bluetooth detection rate for better battery performance.
        /// </summary>
        internal static string PerformanceBluetooth {
            get {
                return ResourceManager.GetString("PerformanceBluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application may have more difficulty detecting public art in your vicinity.
        /// </summary>
        internal static string PerformanceBluetoothDetails {
            get {
                return ResourceManager.GetString("PerformanceBluetoothDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease GPS accuracy for better battery performance.
        /// </summary>
        internal static string PerformanceGPS {
            get {
                return ResourceManager.GetString("PerformanceGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application may have more difficulty finding your current location.
        /// </summary>
        internal static string PerformanceGPSDetails {
            get {
                return ResourceManager.GetString("PerformanceGPSDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all your Favorites?.
        /// </summary>
        internal static string RemoveAllFavoritesBody {
            get {
                return ResourceManager.GetString("RemoveAllFavoritesBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All Favorites.
        /// </summary>
        internal static string RemoveAllFavoritesTitle {
            get {
                return ResourceManager.GetString("RemoveAllFavoritesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this item from Favorites?.
        /// </summary>
        internal static string RemoveFromFavoritesBody {
            get {
                return ResourceManager.GetString("RemoveFromFavoritesBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event has already been removed from Favorites.
        /// </summary>
        internal static string RemoveFromFavoritesFailureBody {
            get {
                return ResourceManager.GetString("RemoveFromFavoritesFailureBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Removed Event.
        /// </summary>
        internal static string RemoveFromFavoritesFailureTitle {
            get {
                return ResourceManager.GetString("RemoveFromFavoritesFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Favorites.
        /// </summary>
        internal static string RemoveFromFavoritesTitle {
            get {
                return ResourceManager.GetString("RemoveFromFavoritesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to default settings.
        /// </summary>
        internal static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset to settings to their default values?.
        /// </summary>
        internal static string ResetSettingsWarning {
            get {
                return ResourceManager.GetString("ResetSettingsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select building.
        /// </summary>
        internal static string SelectBuilding {
            get {
                return ResourceManager.GetString("SelectBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me events within the next .
        /// </summary>
        internal static string TimeRangeFilterHeader {
            get {
                return ResourceManager.GetString("TimeRangeFilterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today at .
        /// </summary>
        internal static string TodayAt {
            get {
                return ResourceManager.GetString("TodayAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Units.
        /// </summary>
        internal static string UnitAll {
            get {
                return ResourceManager.GetString("UnitAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arts And Science.
        /// </summary>
        internal static string UnitArtsAndScience {
            get {
                return ResourceManager.GetString("UnitArtsAndScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John Molson School of Business.
        /// </summary>
        internal static string UnitBusiness {
            get {
                return ResourceManager.GetString("UnitBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENCS.
        /// </summary>
        internal static string UnitENCS {
            get {
                return ResourceManager.GetString("UnitENCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine Arts.
        /// </summary>
        internal static string UnitFineArts {
            get {
                return ResourceManager.GetString("UnitFineArts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string UnitMain {
            get {
                return ResourceManager.GetString("UnitMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offices.
        /// </summary>
        internal static string UnitOffices {
            get {
                return ResourceManager.GetString("UnitOffices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit.
        /// </summary>
        internal static string Visit {
            get {
                return ResourceManager.GetString("Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Website.
        /// </summary>
        internal static string VisitWebsite {
            get {
                return ResourceManager.GetString("VisitWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualise.
        /// </summary>
        internal static string Visualise {
            get {
                return ResourceManager.GetString("Visualise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  was tapped..
        /// </summary>
        internal static string WasTapped {
            get {
                return ResourceManager.GetString("WasTapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
